name: EE-Task-App-CI-Build-Docker-Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] # for my PR testing

jobs:
  EE-Task-App-CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Typescript compilation 
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0
        cache: 'yarn'
    - run: yarn install
    - run: tsc
    - name: Formatting
      run:  yarn prettier --check 'src/**/*.ts'
    - name: Testing
      run: yarn jest
    - name: Testing Coverage
      run: yarn jest --coverage
    - name: Tar and upload coverage files as artifacts
      run: tar -cvf coverage.tar coverage
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: coverage.tar


  build-and-push-image:
    needs: EE-Task-App-CI # only after the CI test pass build the container
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Log in to the Container registry
      #   uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: Dockerfile
          #push: true
          tags: ee-task-app-ci:latest
